Adding webpage content
jaimevillegas/Hello-Microverse pull request #1
Opened 2023-01-10 17:40 UTC by jaimevillegas

2023-01-10 18:08 UTC, osamaashraf6 requested changes
Hi @jaimevillegas 👋, 

Good job so far! 👏🥳
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights ✔️
- [x] Good commit messages.
- [x] No linter errors. 💯
- [x] Good usage in correcting GitHub flow


## Required Changes ♻️

- [ ] You did well 🎈🪄on the project, but I see that you didn't write a pull request for this project, so please😃 add a Pull Request which should have a descriptive title telling you what changes are inside and Pull Request should have a summary describing introduced changes in more detail.💯

- [ ] Good job👍with the project you are almost there you finish the project don't worry 🥳your code is good, but there are some issues to be fixed, so please check the comments to know what I am talking about 😊, so kindly👇💯 check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-10 18:08 UTC, osamaashraf6 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [x] Great job 👌at updating the README file, but I see that the MIT LICENCE file is broken☺️, so kindly try to fix the LICENCE file by adding it from the GitHub💯

2023-01-10 18:08 UTC, osamaashraf6 commented on .gitignore
> +test.md
- [ ] You did well 👌at implementing the requirements of the project💯, but I see that you put the ``` test.md ``` file in the gitignore, but you didn't add the file to the directory, so please😊 put the test.md file in the directory of the project and put this sentence which inside the requirements.

2023-01-10 19:52 UTC, jaimevillegas commented
Hello @osamaashraf6 !

Thank you a lot for reviewing my code. I have worked on the tasks that you left me, and I think it is all resolved now.

If there are some other thing to do, don't hesitate to tell me! 

Best regards!

2023-01-11 15:22 UTC, christianbiring1 approved these changes
Hi @jaimevillegas , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights
- [ ] lInters checks are green :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 15:27 UTC, merged